version: 0.2
phases:
  install:
    commands:
      - echo "Installing utilidades..."
      - yum -y install jq || True
  build:
    commands:
      - echo "Validating CloudFormation templates..."
      - aws cloudformation validate-template --template-body file://templates/s3_group_policy.yaml
      - aws cloudformation validate-template --template-body file://templates/ec2_s3_role.yaml
      - echo "Validation complete"

artifacts:
  files:
    - templates/*.yaml
